import { nodeListStateInterface } from './nodeListStateInterface';

export const presetNodeState: nodeListStateInterface[] = [
    {
        index: 0,
        value: 0,
        elevation: 5,
        className: '',
        xPosition: 204.9,
        yPosition: 317.2,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 1,
        value: 1,
        elevation: 5,
        className: '',
        xPosition: 887.3,
        yPosition: 226.0,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 2,
        value: 2,
        elevation: 5,
        className: '',
        xPosition: 360.0,
        yPosition: 263.0,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 3,
        value: 3,
        elevation: 5,
        className: '',
        xPosition: 794.7,
        yPosition: 99,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 4,
        value: 4,
        elevation: 5,
        className: '',
        xPosition: 491.1,
        yPosition: 494,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 5,
        value: 5,
        elevation: 5,
        className: '',
        xPosition: 458.1,
        yPosition: 351.4,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 6,
        value: 6,
        elevation: 5,
        className: '',
        xPosition: 252.2,
        yPosition: 119.0,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 7,
        value: 7,
        elevation: 5,
        className: '',
        xPosition: 812.1,
        yPosition: 496.2,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 8,
        value: 8,
        elevation: 5,
        className: '',
        xPosition: 505.7,
        yPosition: 201.6,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 9,
        value: 9,
        elevation: 5,
        className: '',
        xPosition: 584.9,
        yPosition: 77.7,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 10,
        value: 10,
        elevation: 5,
        className: '',
        xPosition: 632.7,
        yPosition: 397,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 11,
        value: 11,
        elevation: 5,
        className: '',
        xPosition: 821.1,
        yPosition: 368.7,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 12,
        value: 12,
        elevation: 5,
        className: '',
        xPosition: 257.8,
        yPosition: 504.6,
        fill: '#9e9e9e',
        ref: null,
    },
    {
        index: 13,
        value: 13,
        elevation: 5,
        className: '',
        xPosition: 719.0,
        yPosition: 253.3,
        fill: '#9e9e9e',
        ref: null,
    }
]